### ISSUE TITLE
Support catalog / table and column unquoting

### ISSUE THREAD

**Issue by hayssams** [starlake-ai/jsqltranspiler#31]
Shouldn't the names be unquoted in `new Table(alias != null ? alias.getName() : t.tableName));`  in file JSQLColumnResolver ?

**Comment by manticore-projects** [comment]
I am going to rework this part adding `getUnquotedIdentifier()` methods to `Table`, `Column` and `Database` in JSQLParser directly.

**Comment by manticore-projects** [comment]
fixed, please verify and close this issue when you are good.

**Comment by hayssams** [comment]
Yes it's almost fixed. Thanks.
We still have a edge case specific to BigQuery with the use of the backticks.
The following select statements should be treated the same way:
```
select * from dataset.table         #(unquoted)
select * from `dataset.table`       #(quoted)
select * from `dataset`.`table`   #(quoted)
```

JSQLTranspiler successfully handle case 1 & 3 but fails to handle the second case with the following error:

```
Exception in thread "main" java.lang.RuntimeException: Table dataset.table does not exist in the given Schema 
	at ai.starlake.transpiler.schema.JdbcMetaData.getColumn(JdbcMetaData.java:264)
	at ai.starlake.transpiler.JSQLExpressionColumnResolver.getJdbcColumn(JSQLExpressionColumnResolver.java:98)
	at ai.starlake.transpiler.JSQLExpressionColumnResolver.visit(JSQLExpressionColumnResolver.java:341)
	at ai.starlake.transpiler.JSQLExpressionColumnResolver.visit(JSQLExpressionColumnResolver.java:51)
	at net.sf.jsqlparser.schema.Column.accept(Column.java:166)
```

**Comment by manticore-projects** [comment]
Case 2 breaks with any and every normal convention how quoting works.
But I will try to make it happen.

**Comment by hayssams** [comment]
Yes you're right! It's weird that BQ accept it.
You made it work.
Thank you
